name: test-java

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
          cache: 'maven'
      # Sanity check
      - run: make results/rtptorrent/CloudifySource@cloudify/com.smartbear.tcpbench.engines.InitialOrder.csv
